/*
 / _____)             _              | |
( (____  _____ ____ _| |_ _____  ____| |__
 \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 _____) ) ____| | | || |_| ____( (___| | | |
(______/|_____)_|_|_| \__)_____)\____)_| |_|
    (C)2015 Semtech

Description: End device commissioning parameters

License: Revised BSD License, see LICENSE.TXT file include in the project

Maintainer: Miguel Luis and Gregory Cristian
*/
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     1

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      true

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define LORAWAN_DEVICE_EUI                         { 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0xE3, 0x77 }

/*!
 * Application IEEE EUI (big endian)
 */
#define LORAWAN_APPLICATION_EUI                    { 0x70, 0xB3, 0xD5, 0x7E, 0xF0, 0x00, 0x3C, 0x3E }

/*!
 * AES encryption/decryption cipher application key
 */
#define LORAWAN_APPLICATION_KEY                    { 0x72, 0xA0, 0x0A, 0x83, 0x14, 0xDC, 0xF9, 0x84, 0xBC, 0x2C, 0x7C, 0x5C, 0xD9, 0x65, 0xC4, 0x48 }

/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0x00

/*!
 * Device address on the network (big endian) - ONLY FOR ABP ACTIVATION
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
//----#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x26011B11

/*!
 * AES encryption/decryption cipher network session key
 */
//----#define LORAWAN_NWKSKEY                             { 0x25, 0x9D, 0xA7, 0xF8, 0x56, 0x3E, 0x03, 0x83, 0xA6, 0xE5, 0xF8, 0x37, 0x4C, 0x18, 0x27, 0xBF }

/*!
 * AES encryption/decryption cipher application session key
 */
//-----#define LORAWAN_APPSKEY                             { 0x83, 0xF0, 0x23, 0x93, 0x99, 0xCF, 0xEE, 0x96, 0x40, 0x2C, 0x8A, 0xCB, 0x33, 0x6E, 0x90, 0x43 }
#endif // __LORA_COMMISSIONING_H__
